name: app_template
description: "An app template."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.10.3

dependencies:
  awesome_flutter_extensions: ^2.0.1
  dart_mappable: ^4.6.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^3.0.3
  flutter_smart_dialog: ^4.9.8+9
  formz: ^0.8.0
  go_router: ^17.0.0
  intl: any
  logging: ^1.3.0
  package_info_plus: ^9.0.0
  recase: ^4.1.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  tinycolor2: ^3.0.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  dart_mappable_builder: ^4.6.3
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
